MUSCLE (3.8) multiple sequence alignment


GRIN2C          ------MGGALGPALLLTSLF------------GAWAGLGP-GQGEQG---MTVAVVFSS
GRIN2D          MRGAGGPRGPRGPAKMLLLLALACASPFPEEAPGPGGAGGP-GGGLGGARPLNVALVFSG
GRIN2A          -------MGRVGYWTLLVLPAL-----------LVWRGPAPSAAAEKGPPALNIAVMLGH
GRIN2B          MKPRAECCSPK-FWLVLAVLAV----------------SGSRARSQKSPPSIGIAVILVG
                        .      :*                      .. . .  .   : :*:::  

GRIN2C          SGPPQA-QFRARLTPQSFLDLP---LEIQPLTVGVNTTNPSSLLTQICGLLGAAHVHGIV
GRIN2D          PAYAAE---AARLGPAVAAAVRSPGLDVRPVALVLNGSDPRSLVLQLCDLLSGLRVHGVV
GRIN2A          SHDVTERELRTLWGPEQAAGLP---LDVNVVALLMNRTDPKSLITHVCDLMSGARIHGLV
GRIN2B          TSDEVA--IKDAHEKDDFHHLS---VVPRVELVAMNETDPKSIITRICDLMSDRKIQGVV
                .                   :    :  .   : :* ::* *:: .:*.*:.  .::*:*

GRIN2C          FEDNVDTEAVAQILDFISSQTHVPILSISGGSAVVLTPKEPGSAFLQLGVSLEQQLQVLF
GRIN2D          FEDDSRAPAVAPILDFLSAQTSLPIVAVHGGAALVLTPKEKGSTFLQLGSSTEQQLQVIF
GRIN2A          FGDDTDQEAVAQMLDFISSHTFVPILGIHGGASMIMADKDPTSTFFQFGASIQQQATVML
GRIN2B          FADDTDQEAIAQILDFISAQTLTPILGIHGGSSMIMADKDESSMFFQFGPSIEQQASVML
                * *:    *:* :***:*::*  **:.: **:::::: *:  * *:*:* * :**  *::

GRIN2C          KVLEEYDWSAFAVITSLHPGHALFLEGVRAVADASHVSWRLLDVVTLELGPGGPRARTQR
GRIN2D          EVLEEYDWTSFVAVTTRAPGHRAFLSYIEVLTDGSLVGWEHRGALTLD--PGAGEAVLSA
GRIN2A          KIMQDYDWHVFSLVTTIFPGYREFISFVKTTVDNSFVGWDMQNVITLDTSFE--DAKTQV
GRIN2B          NIMEEYDWYIFSIVTTYFPGYQDFVNKIRSTIENSFVGWELEEVLLLDMSLDDGDSKIQN
                :::::***  *  :*:  **:  *:. :    : * *.*    .: *:       :  . 

GRIN2C          LLRQLDAPVFVAYCSREEAEVLFAEAAQAGLVGPGHVWLV--PNLALGSTDAPPAT----
GRIN2D          QLRSVSAQIRLLFCAREEAEPVFRAAEEAGLTGSGYVWFMVGPQLAGGGGSGAPGEPPLL
GRIN2A          QLKKIHSSVILLYCSKDEAVLILSEARSLGLTGYDFFWIV--PSLVSGNTELIPKE----
GRIN2B          QLKKLQSPIILLYCTKEEATYIFEVANSVGLTGYGYTWIV--PSLVAGDTDTVPAE----
                 *..: : : : :*:.:**  ::  * . **.* .. *::  *.*. *. .  *      

GRIN2C          -----FPVGLISVVTESWRLSLRQKVRDGVAILALGAHSYWRQHGTLPAPAGDCRVHPGP
GRIN2D          PGGAPLPAGLFAVRSAGWRDDLARRVAAGVAVVARGAQALLRDYGFLPELGHDCRAQ--N
GRIN2A          -----FPSGLISVSYDDWDYSLEARVRDGIGILTTAASSMLEKFSYIPEAKASCYGQMER
GRIN2B          -----FPTGLISVSYDEWDYGLPARVRDGIAIITTAASDMLSEHSFIPEPKSSCYNTHEK
                     :* **::*    *  .*  .*  *:.::: .*     ... :*    .*      

GRIN2C          VSPAREAFYRHLLNVTWEGRDFSFSPGGYLVQPTMVVIALNRHRLWEMVGRWEHGVLYMK
GRIN2D          RTHRGESLHRYFMNITWDNRDYSFNEDGFLVNPSLVVISLTRDRTWEVVGSWEQQTLRLK
GRIN2A          PEVPMHTLHPFMVNVTWDGKDLSFTEEGYQVHPRLVVIVLNKDREWEKVGKWENHTLSLR
GRIN2B          RIYQSNMLNRYLINVTFEGRNLSFSEDGYQMHPKLVIILLNKERKWERVGKWKDKSLQMK
                       :  .::*:*::..: **.  *: ::* :*:* *.. * ** ** *:   * :.

GRIN2C          YPVWPRYSASLQPVVDSRHLTVATLEERPFVIVESPDPGTGGCVPNTVPCRRQSNHTFSS
GRIN2D          YPLWSRYGRFLQPVDDTQHLTVATLEERPFVIVEPADPISGTCIRDSVPCRSQLNRTHSP
GRIN2A          HAVWPRYKSFSDCEPDDNHLSIVTLEEAPFVIVEDIDPLTETCVRNTVPCRKFVKINNST
GRIN2B          YYVWPRMCPETEEQEDD-HLSIVTLEEAPFVIVESVDPLSGTCMRNTVPCQKRI-VTENK
                : :*.*     :   *  **::.**** ******  ** :  *: ::***.     . . 

GRIN2C          GDVAP-YTKLCCKGFCIDILKKLARVVKFSYDLYLVTNGKHGKRVRGVWNGMIGEVYYKR
GRIN2D          PPDAPRPEKRCCKGFCIDILKRLAHTIGFSYDLYLVTNGKHGKKIDGVWNGMIGEVFYQR
GRIN2A          NEGMN--VKKCCKGFCIDILKKLSRTVKFTYDLYLVTNGKHGKKVNNVWNGMIGEVVYQR
GRIN2B          TDEEPGYIKKCCKGFCIDILKKISKSVKFTYDLYLVTNGKHGKKINGTWNGMIGEVVMKR
                        * ***********.::. : *:*************.: ..********  :*

GRIN2C          ADMAIGSLTINEERSEIVDFSVPFVETGISVMVARSNGTVSPSAFLEPYSPAVWVMMFVM
GRIN2D          ADMAIGSLTINEERSEIVDFSVPFVETGISVMVARSNGTVSPSAFLEPYSPAVWVMMFVM
GRIN2A          AVMAVGSLTINEERSEVVDFSVPFVETGISVMVSRSNGTVSPSAFLEPFSASVWVMMFVM
GRIN2B          AYMAVGSLTINEERSEVVDFSVPFIETGISVMVSRSNGTVSPSAFLEPFSADVWVMMFVM
                * **:***********:*******:********:**************:*. ********

GRIN2C          CLTVVAITVFMFEYFSPVSYNQNLTRGKKSGGPAFTIGKSVWLLWALVFNNSVPIENPRG
GRIN2D          CLTVVAVTVFIFEYLSPVGYNRSLATGKRPGGSTFTIGKSIWLLWALVFNNSVPVENPRG
GRIN2A          LLIVSAIAVFVFEYFSPVGYNRNLAKGKAPHGPSFTIGKAIWLLWGLVFNNSVPVQNPKG
GRIN2B          LLIVSAVAVFVFEYFSPVGYNRCLADGREPGGPSFTIGKAIWLLWGLVFNNSVPVQNPKG
                 * * *::**:***:***.**. *: *. . *.:*****::****.********::**.*

GRIN2C          TTSKIMVLVWAFFAVIFLASYTANLAAFMIQEQYIDTVSGLSDKKFQRPQDQYPPFRFGT
GRIN2D          TTSKIMVLVWAFFAVIFLASYTANLAAFMIQEEYVDTVSGLSDRKFQRPQEQYPPLKFGT
GRIN2A          TTSKIMVSVWAFFAVIFLASYTANLAAFMIQEEFVDQVTGLSDKKFQRPHDYSPPFRFGT
GRIN2B          TTSKIMVSVWAFFAVIFLASYTANLAAFMIQEEYVDQVSGLSDKKFQRPNDFSPPFRFGT
                ******* ************************:::* *:****.*****::  **:.***

GRIN2C          VPNGSTERNIRSNYRDMHTHMVKFNQRSVEDALTSLKMGKLDAFIYDAAVLNYMAGKDEG
GRIN2D          VPNGSTEKNIRSNYPDMHSYMVRYNQPRVEEALTQLKAGKLDAFIYDAAVLNYMARKDEG
GRIN2A          VPNGSTERNIRNNYPYMHQYMTKFNQKGVEDALVSLKTGKLDAFIYDAAVLNYKAGRDEG
GRIN2B          VPNGSTERNIRNNYAEMHAYMGKFNQRGVDDALLSLKTGKLDAFIYDAAVLNYMAGRDEG
                *******.***.**  ** :* .:**  *::** .** *************** * .***

GRIN2C          CKLVTIGSGKVFATTGYGIAMQKDSHWKRAIDLALLQFLGDGETQKLETVWLSGICQNEK
GRIN2D          CKLVTIGSGKVFATTGYGIALHKGSRWKRPIDLALLQFLGDDEIEMLERLWLSGICHNDK
GRIN2A          CKLVTIGSGYIFATTGYGIALQKGSPWKRQIDLALLQFVGDGEMEELETLWLTGICHNEK
GRIN2B          CKLVTIGSGKVFASTGYGIAIQKDSGWKRQVDLAILQLFGDGEMEELEALWLTGICHNEK
                ********* :**:******::*.* *** :***:**:.**.* : ** :**:***:*:*

GRIN2C          NEVMSSKLDIDNMAGVFYMLLVAMGLALLVFAWEHLVYWKLRHSVPN--SSQLDFLLAFS
GRIN2D          IEVMSSKLDIDNMAGVFYMLLVAMGLSLLVFAWEHLVYWRLRHCLGP--THRMDFLLAFS
GRIN2A          NEVMSSQLDIDNMAGVFYMLAAAMALSLITFIWEHLFYWKLRFCFTGVCSDRPGLLFSIS
GRIN2B          NEVMSSQLDIDNMAGVFYMLGAAMALSLITFICEHLFYWQFRHCFMGVCSGKPGMVFSIS
                 *****:************* .**.*:*:.*  ***.**.:*...    : . .:::::*

GRIN2C          RGIYSCFSG------VQSLASPPRQASPDLTASSAQASVLKMLQAARDMVTT--------
GRIN2D          RGMYSCCSAEAAPPPAKPPPPPQPLPSPAYPAPRPAPGPAPFVPRERASVDRWRRTKGAG
GRIN2A          RGIYSCIHG------VHIEEKK---KSPDFNLTGSQSNMLKLLRSAKNISSM--------
GRIN2B          RGIYSCIHG------VAIEERQSVMNSPTATMNNTHSNILRLLRTAKNMANL--------
                **:***  .      .          **      . ..   ::   .             

GRIN2C          ----AGVSS----SLDRATRTIE------NWGGGRRAPPPSPCPTPRSGPSPCLPTPD--
GRIN2D          PPGGAGLAD----GFHRYYGPIEPQGLGLGLGEARAAPRGAAGRPLSPPAAQ--------
GRIN2A          ----SNMNSSRMDSPKRAADFIQRGSLIMDMVSDKGNLMYSDNRSFQG---KESIFGDNM
GRIN2B          ----SGVNG----SPQSALDFIRRESSVYDISEHRRSFTHSDCKSYNNPPCEENLFSDYI
                    :.: .    .       *       .    .     :   .               

GRIN2C          ----------------------------PPPEPSPTGWG-----------PPDGGRAALV
GRIN2D          ----------------------------PPQKPPPSYFAIVRDK--EPAEPPAGAFPGFP
GRIN2A          NELQTFVANRQKDNLNNYVFQGQHPLTLNESNPNTVEVAVSTES--KANSRPRQLWKKSV
GRIN2B          SEVERTFGNLQLKDSNVYQDHYH-----HHHRPHSIGSASSIDGLYDCDNPPFTTQSRSI
                                                * .   .            *        

GRIN2C          RRAPQ------PPGRPPTPGPPLSDVSRVSRR---PAWEARWPV----RTGHCGRHLSAS
GRIN2D          SPPAP------PAAAATAVGPPLCRLAFEDES---PPAPARWPRSDPESQPLLGPGAGGA
GRIN2A          DSIRQDSLSQNPVSQRDEATAENRTHSLKSPRYL-PEEMAHSDISETSNRATCHREPDNS
GRIN2B          SKKPLDIGL--PSSKHSQLSDLYGKFSFKSDRYSGHDDLIRSDVSDISTHTVTYGNIEGN
                           * .            :  .          .                   

GRIN2C          --------------ERPLS---PARCHYSSFP-RADRSGRPFLPLFP---ELEDLPLLGP
GRIN2D          GGTGGAGG------GAPAA---PPPC-------RAAPPPCPYLDLEPSPSDSEDSESLGG
GRIN2A          KNHKTKDNF-----KRSVASKYPKDCSEVERTYLKTKSSSPRDKIYTIDGEKEPGFHLDP
GRIN2B          AAKRRKQQYKDSLKKRPASAKSRREFDEIELAYRRRPPRSPDHKRYFRDKEGLRDFYLDQ
                                . :                  .  *         :      *. 

GRIN2C          EQLARREALL------------------------------------------------HA
GRIN2D          ASLGGLEPWW-FADFPYPYAERLGP-----------------------------------
GRIN2A          PQFVENVTLPENVDFPDPYQDPSENFRKGDSTLPMNRNPLHNEEGLSNNDQYKLYSKHFT
GRIN2B          FRTKENSPHWEHVDLTDIYKERSDDFKR-DSVSGGGPCTNRSHIKHGTGDKHGVVSGVPA
                       .                                                    

GRIN2C          AWARGSRPRHASLPSSVAEAFAR--PSSLPAGCTGPACARPDGHSACRRLAQAQSMCLPI
GRIN2D          -----PPGRYWSV--DKLGGWRAGSWDYLPP-RSGPAAWH------CRHCASLELLPPPR
GRIN2A          LKDKGSPHSETSERYRQNSTHCRSCLSNMPT-YSGHFTMRSP-----FKCDACLRMGNLY
GRIN2B          PWEKNLTNVEWED--RSGGNFCRSCPSKLHN-YSTTVTGQNSGRQACIRCEACKKAGNLY
                           .              . :    :     .        .           

GRIN2C          YREACQEGEQAGAPA-----------------W--------QHRQHVCLHAHAH-----L
GRIN2D          HLSCSHDGLDGGWWAPP------------PPPWA-AGPLPRRRARCGCPRSHPH-----R
GRIN2A          DIDEDQMLQETGNPATGEQV--------YQQDWAQNNALQLQKNKLRISRQHSYDNIVDK
GRIN2B          DISEDNSLQELDQPAAPVAVTSNASTTKYPQSPTNSKAQKKNRNKLR--RQHSYDTFVDL
                  .  :   : .  *                          .. .    . *.:      

GRIN2C          PFC-WGAVCPHLPPCASHGSWLSGAW---------------------GPLGHR-------
GRIN2D          PRA-SHRTPAAAAPHHHRHRRAAGGW-------------------DLPPPAPT-------
GRIN2A          PRELDLSRPSRSISLKDRERLLEGNFYGSLFSVPS--SKLSGKKSSLFPQGLEDSKR---
GRIN2B          QKE-EAALAPRSVSLKDKGRFMDGSPYAHMFEMSAGESTFANNKSSVPTAGHHHHNNPGG
                         .   .   .     *                        . .         

GRIN2C          ----GRTL-------------------------------------GLGTGYRDSGGLD--
GRIN2D          ----SRSL-------------------------------------EDLSSCPRAAPAR--
GRIN2A          ----SKSLLPDHTSDNPFLHSHRDDQRLVIGRCPSDPYKHSLPSQAVNDSYLRSSLRS--
GRIN2B          GYMLSKSLYPDRVTQNPFIPTFGDDQCLLHG---SKSYFFRQPTVA-GASKARPDFRALV
                    ..:*                                         .   .      

GRIN2C          ------EISRVARGTQGFPGPCTW-----------------------------RRISSLE
GRIN2D          ------RLTGPSRHARRCPHAAHWGPPLPTASHRRH------RGGDLGTRRGSAHFSSLE
GRIN2A          ------TASYCSRDSRGHNDVYISEHVMPYAANKNNMYSTPRVLNSCSNRRVYKKMPSIE
GRIN2B          TNKPVVSALHGAVPARFQKDICIGNQSNPCVPNNKN----PRAFNGSSNGHVYEKLSSIE
                           :  :.                                      .:.*:*

GRIN2C          SEV
GRIN2D          SEV
GRIN2A          SDV
GRIN2B          SDV
                *:*
