MUSCLE (3.8) multiple sequence alignment


SCN11A          -MDDRCYPVIFPDERNFRPFTSDSLAAIEKRIAIQKEKKK------SKDQTGEVPQPRPQ
SCN7A           -------MLASPEPKGLVPFTKESFELIKQHIAKT-----------HNED-HEEEDLKPT
SCN10A          ----MEFPIGSLETNNFRRFTPESLVEIEKQIAAKQGTKKAREK--HREQKDQEEKPRPQ
SCN5A           ----MANFLLPRGTSSFRRFTRESLAAIEKRMAEKQARGSTTLQE-SREGLPEEEAPRPQ
SCN4A           MARPSLCTLVPLGPECLRPFTRESLAAIEQRAVEEEARLQRN----KQME-IEEPERKPR
SCN8A           ---MAARLLAPPGPDSFKPFTPESLANIERRIAESKLKKPPKADGSHRED-DEDSKPKPN
SCN9A           -----MAMLPPPGPQSFVHFTKQSLALIEQRIAERKSKEPKE----EKKD-DDEEAPKPS
SCN3A           ---MAQALLVPPGPESFRLFTRESLAAIEKRAAEEKAKKPKK----EQDN-DDENKPKPN
SCN2A           ---MAQSVLVPPGPDSFRFFTRESLAAIEQRIAEEKAKRPKQ----ERKDEDDENGPKPN
SCN1A           ---MEQTVLVPPGPDSFNFFTRESLAAIERRIAEEKAKNPKP----DKKD-DDENGPKPN
                        :       :  ** :*:  *:.. .              .    :    .* 

SCN11A          LDLKASRKLPKLYGDIPRELIGKPLEDLDPFYRNHK-TFMVLNRKRTIYRFSAKHALFIF
SCN7A           PDLEVGKKLPFIYGNLSQGMVSEPLEDVDPYYYKKKNTFIVLNKNRTIFRFNAASILCTL
SCN10A          LDLKACNQLPKFYGELPAELIGEPLEDLDPFYSTHR-TFMVLNKGRTISRFSATRALWLF
SCN5A           LDLQASKKLPDLYGNPPQELIGEPLEDLDPFYSTQK-TFIVLNKGKTIFRFSATNALYVL
SCN4A           SDLEAGKNLPMIYGDPPPEVIGIPLEDLDPYYSNKK-TFIVLNKGKAIFRFSATPALYLL
SCN8A           SDLEAGKSLPFIYGDIPQGLVAVPLEDFDPYYLTQK-TFVVLNRGKTLFRFSATPALYIL
SCN9A           SDLEAGKQLPFIYGDIPPGMVSEPLEDLDPYYADKK-TFIVLNKGKTIFRFNATPALYML
SCN3A           SDLEAGKNLPFIYGDIPPEMVSEPLEDLDPYYINKK-TFIVMNKGKAIFRFSATSALYIL
SCN2A           SDLEAGKSLPFIYGDIPPEMVSVPLEDLDPYYINKK-TFIVLNKGKAISRFSATPALYIL
SCN1A           SDLEAGKNLPFIYGDIPPEMVSEPLEDLDPYYINKK-TFIVLNKGKAIFRFSATSALYIL
                 **:. ..** :**: .  ::. ****.**:*  :. **:*:*. .:: **.*   *  :

SCN11A          GPFNSIRSLAIRVSVHSLFSMFIIGTVIINCVFMATGPAKNSNSNNTDIAECVFTGIYIF
SCN7A           SPFNCIRRTTIKVLVHPFFQLFILISVLIDCVFM----SLTNLPKWRPVLENTLLGIYTF
SCN10A          SPFNLIRRTAIKVSVHSWFSLFITVTILVNCVCM----TRTDLPE---KIEYVFTVIYTF
SCN5A           SPFHPIRRAAVKILVHSLFNMLIMCTILTNCVFM----AQHDPPPWTKYVEYTFTAIYTF
SCN4A           SPFSVVRRGAIKVLIHALFSMFIMITILTNCVFM----TMSDPPPWSKNVEYTFTGIYTF
SCN8A           SPFNLIRRIAIKILIHSVFSMIIMCTILTNCVFM----TFSNPPDWSKNVEYTFTGIYTF
SCN9A           SPFSPLRRISIKILVHSLFSMLIMCTILTNCIFM----TMNNPPDWTKNVEYTFTGIYTF
SCN3A           TPLNPVRKIAIKILVHSLFSMLIMCTILTNCVFM----TLSNPPDWTKNVEYTFTGIYTF
SCN2A           TPFNPIRKLAIKILVHSLFNMLIMCTILTNCVFM----TMSNPPDWTKNVEYTFTGIYTF
SCN1A           TPFNPLRKIAIKILVHSLFSMLIMCTILTNCVFM----TMSNPPDWTKNVEYTFTGIYTF
                 *:  :*  ::.: :*. *.::*  ::: :*: *    :  . .      * .:  ** *

SCN11A          EALIKILARGFILDEFSFLRDPWNWLDSIVIGIAIVSYIPGITIKLLPLRTFRVFRALKA
SCN7A           EILVKLFARGVWAGSFSFLGDPWNWLDFSVTVFEVIIRYSPLD-FIPTLQTARTLRILKI
SCN10A          EALIKILARGFCLNEFTYLRDPWNWLDFSVITLAYVGTAIDLR-GISGLRTFRVLRALKT
SCN5A           ESLVKILARGFCLHAFTFLRDPWNWLDFSVIIMAYVSENIKLG-NLSALRTFRVLRALKT
SCN4A           ESLIKILARGFCVDDFTFLRDPWNWLDFSVIMMAYLTEFVDLG-NISALRTFRVLRALKT
SCN8A           ESLVKIIARGFCIDGFTFLRDPWNWLDFSVIMMAYITEFVNLG-NVSALRTFRVLRALKT
SCN9A           ESLVKILARGFCVGEFTFLRDPWNWLDFVVIVFAYLTEFVNLG-NVSALRTFRVLRALKT
SCN3A           ESLIKILARGFCLEDFTFLRDPWNWLDFSVIVMAYVTEFVDLG-NVSALRTFRVLRALKT
SCN2A           ESLIKILARGFCLEDFTFLRDPWNWLDFTVITFAYVTEFVNLG-NVSALRTFRVLRALKT
SCN1A           ESLIKIIARGFCLEDFTFLRDPWNWLDFTVITFAYVTEFVDLG-NVSALRTFRVLRALKT
                * *:*::***.    *::* *******  *  :  :     :   :  *.* *.:* ** 

SCN11A          ISVVSRLKVIVGALLRSVKKLVNVIILTFFCLSIFALVGQQLFMGSLNLKCI--------
SCN7A           IPLNQGLKSLVGVLIHCLKQLIGVIILTLFFLSIFSLIGMGLFMGNLKHKCFRWP-----
SCN10A          VSVIPGLKVIVGALIHSVKKLADVTILTIFCLSVFALVGLQLFKGNLKNKCVK-------
SCN5A           ISVIPGLKTIVGALIQSVKKLADVMVLTVFCLSVFALIGLQLFMGNLRHKCVR-------
SCN4A           ITVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALVGLQLFMGNLRQKCVRWPPPFN-
SCN8A           ISVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALIGLQLFMGNLRNKCVVWP-----
SCN9A           ISVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALIGLQLFMGNLKHKCFR-------
SCN3A           ISVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALIGLQLFMGNLRNKCLQWPPSDSA
SCN2A           ISVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALIGLQLFMGNLRNKCLQWPPDNSS
SCN1A           ISVIPGLKTIVGALIQSVKKLSDVMILTVFCLSVFALIGLQLFMGNLRNKCIQWPPTNAS
                :.:   ** :**.*:..:*:* .* :**.* **:*:*:*  ** *.*. **.        

SCN11A          --------------------------------------------SRDCKNISNPEAY---
SCN7A           -----------QENENETLHNR----------------------TGNPY-------YIRE
SCN10A          ---------------NDMAVNE----------------------TTNYSSHRKPDIYINK
SCN5A           ----------NFTALNGTNGSV----------------------EADGLVWESLDLYLSD
SCN4A           -DTNTTWYSNDTWYGNDTWYGNEMWYGNDSWYANDTWNSHASWATNDTFDWDA---YISD
SCN8A           ------------INFNESYLEN----------------------GTKGFDWEE---YINN
SCN9A           ----------NSLENNETLESI-----------------------MNTLESEE-----DF
SCN3A           FETNTTSYFNGTMDSNGTFVNV----------------------TMSTFNWKD---YIGD
SCN2A           FEINITSFFNNSLDGNGTTFNR----------------------TVSIFNWDE---YIED
SCN1A           LEEHSIE-KNITVNYNGTLINE----------------------TVFEFDWKS---YIQD
                                                                            

SCN11A          DHCFEKKENSPEFKMCGIWMGNSACSIQYECKHTKINPDYNYTNFDNFGWSFLAMFRLMT
SCN7A           TENFYYLEGERYALLCGNRTDAGQCPEGYVCVKAGINPDQGFTNFDSFGWALFALFRLMA
SCN10A          R-------GTSDPLLCGNGSDSGHCPDGYICLKTSDNPDFNYTSFDSFAWAFLSLFRLMT
SCN5A           PENYLLKNGTSDVLLCGNSSDAGTCPEGYRCLKAGENPDHGYTSFDSFAWAFLALFRLMT
SCN4A           EGNFYFLEGSNDALLCGNSSDAGHCPEGYECIKTGRNPNYGYTSYDTFSWAFLALFRLMT
SCN8A           KTNFYTVPGMLEPLLCGNSSDAGQCPEGYQCMKAGRNPNYGYTSFDTFSWAFLALFRLMT
SCN9A           RKYFYYLEGSKDALLCGFSTDSGQCPEGYTCVKIGRNPDYGYTSFDTFSWAFLALFRLMT
SCN3A           DSHFYVLDGQKDPLLCGNGSDAGQCPEGYICVKAGRNPNYGYTSFDTFSWAFLSLFRLMT
SCN2A           KSHFYFLEGQNDALLCGNSSDAGQCPEGYICVKAGRNPNYGYTSFDTFSWAFLSLFRLMT
SCN1A           SRYHYFLEGFLDALLCGNSSDAGQCPEGYMCVKAGRNPNYGYTSFDTFSWAFLSLFRLMT
                        .     :**   . . *.  * * :   **: .:*.:*.*.*:::::****:

SCN11A          QDSWEKLYQQTLRTTGLYSVFFFIVVIFLGSFYLINLTLAVVTMAYEEQNKNVAAEIEAK
SCN7A           QDYPEVLYHQILYASGKVYMIFFVVVSFLFSFYMASLFLGILAMAYEEEKQRVGEISKKI
SCN10A          QDSWERLYQQTLRTSGKIYMIFFVLVIFLGSFYLVNLILAVVTMAYEEQNQATTDEIEAK
SCN5A           QDCWERLYQQTLRSAGKIYMIFFMLVIFLGSFYLVNLILAVVAMAYEEQNQATIAETEEK
SCN4A           QDYWENLFQLTLRAAGKTYMIFFVVIIFLGSFYLINLILAVVAMAYAEQNEATLAEDKEK
SCN8A           QDYWENLYQLTLRAAGKTYMIFFVLVIFVGSFYLVNLILAVVAMAYEEQNQATLEEAEQK
SCN9A           QDYWENLYQQTLRAAGKTYMIFFVVVIFLGSFYLINLILAVVAMAYEEQNQANIEEAKQK
SCN3A           QDYWENLYQLTLRAAGKTYMIFFVLVIFLGSFYLVNLILAVVAMAYEEQNQATLEEAEQK
SCN2A           QDFWENLYQLTLRAAGKTYMIFFVLVIFLGSFYLINLILAVVAMAYEEQNQATLEEAEQK
SCN1A           QDFWENLYQLTLRAAGKTYMIFFVLVIFLGSFYLINLILAVVAMAYEEQNQATLEEAEQK
                **  * *::  * ::*   ::**::: *: ***: .* *.:::*** *:::      :  

SCN11A          EKMFQEAQQLLKEEKEALVAMGIDRSS--------------------LTSLETSYFTPKK
SCN7A           EPKFQQTGKELQEGNETDEAKTI-------------------------------------
SCN10A          EKKFQEALEMLRKEQEVLAALGIDTTS--------------------LHSHNGSPLTSKN
SCN5A           EKRFQEAMEMLKKEHEALTIRGVDTVS--------------------RSSLEMSPLAPVN
SCN4A           EEEFQQMLEKFKKHQEELEKAKAAQAL---------------------------------
SCN8A           EAEFKAMLEQLKKQQEEAQAAAMATSAGTVSEDAIEEEGEEGGGS-PRSSSEISKLSSKS
SCN9A           ELEFQQMLDRLKKEQEEAEAIAAAAAE----YTSIRRSRIMGL---SESSSETSKLSSKS
SCN3A           EAEFQQMLEQLKKQQEEAQAVAAASAA------SRDFSGIGGLGELLESSSEASKLSSKS
SCN2A           EAEFQQMLEQLKKQQEEAQAAAAAASA----E-SRDFSGAGGIGVFSESSSVASKLSSKS
SCN1A           EAEFQQMIEQLKKQQEAAQQAATATAS----EHSREPSAAGRL---SDSSSEASKLSSKS
                *  *:   . :.: :*                                            

SCN11A          RKLFGNKKRKS-------------------------------------------------
SCN7A           ------------------------------------------------------------
SCN10A          ASERRHRIKPR----VSEGSTEDN--KSPRSDPYNQRR----------------------
SCN5A           SHERRSKRRKR----MSSGTEECGEDRLPKSDSEDGPRAM--------NHLSLTRGLSRT
SCN4A           ----------------EGGEADGD------------------------------------
SCN8A           AKERRNRRKKRKQKELSEGEEKGDPEKVFKSESEDGMRRKAFRLP--DNRIG--RKFSIM
SCN9A           AKERRNRRKKKNQKKLSSGEEKGDAEKLSKSESEDSIRRKSFHLGVEGHRRAHEKRLSTP
SCN3A           AKEWRNRRKKRRQREHLEGNNKGERDSFPKSESEDSVKRSSFLFSMDGNRLTSDKKFCSP
SCN2A           EKELKNRRKKKKQKEQ-SGEEEKN-DRVRKSESEDSIRRKGFRFSLEGSRLTYEKRFSSP
SCN1A           AKERRNRRKKRKQKEQSGGEEKDE-DEFQKSESEDSIRRKGFRFSIEGNRLTYEKRYSSP
                                                                            

SCN11A          ----------------------FFLRESGKDQPPGSDSD---------------------
SCN7A           ------------------------------------------------------------
SCN10A          ----MSFLGLASGKRRASHGSVFHFR--SPGRDISLPEGVTDDG-VFPGDHESHRGSLLL
SCN5A           SMKPRSSRGSIFTFRR---------------RDLGSEADFADDENSTAGESESHHTSLLV
SCN4A           ------------------------------------------------------------
SCN8A           NQSLLSIPGSPFLSRHNSKSSIFSFRGPGRFRDPGSENEFADDEHSTVEESEGRRDSLFI
SCN9A           NQSPLSIRGSLFSARRSSRTSLFSFK--GRGRDIGSETEFADDEHSIFGDNESRRGSLFV
SCN3A           HQSLLSIRGSLFSPRRNSKTSIFSFR--GRAKDVGSENDFADDEHSTFEDSESRRDSLFV
SCN2A           HQSLLSIRGSLFSPRRNSRASLFSFR--GRAKDIGSENDFADDEHSTFEDNDSRRDSLFV
SCN1A           HQSLLSIRGSLFSPRRNSRTSLFSFR--GRAKDVGSENDFADDEHSTFEDNESRRDSLFV
                                                                            

SCN11A          ---------------------------------------EDCQKKPQLLE----------
SCN7A           ------------------------------------------------------------
SCN10A          GGGAGQQGP----------LPRSPLPQPSNPDSRH----------------GEDEHQPPP
SCN5A           PWPLRRTSA-----QGQPSPGTSA---PGHALHGKKNSTVDCNGVVSLLGAGDPEATSPG
SCN4A           ------------------------------PAHGK-----DCNGSLDTSQ-G--------
SCN8A           PIRARERRSSYSGYSGYSQGSRSSRIFPSLRRSVKRNSTVDCNGVVSLIG-GPGSHIG--
SCN9A           PHRPQERRS-----SNISQASRSP---PMLPVNGKMHSAVDCNGVVSLVD-GRSALMLPN
SCN3A           PHRHGERRN-----SNVSQASMSSRMVPGLPANGKMHSTVDCNGVVSLVG-GPSALTSPT
SCN2A           PHRHGERRH-----SNVSQASRASRVLPILPMNGKMHSAVDCNGVVSLVG-GPSTLTS-A
SCN1A           PRRHGERRN-----SNLSQTSRSSRMLAVFPANGKMHSTVDCNGVVSLVG-GPSVPTSPV
                                                                            

SCN11A          --------------------------QTKRLSQNLSLDHFDEHGDPLQRQRALSAVSILT
SCN7A           ---------------------QIEMKKRSPISTDTSLDVLE---DATLRHK---------
SCN10A          TSELAP------------GAVDVSAFDAGQKKTFLSAEYLD---EPFRAQRAMSVVSIIT
SCN5A           SHLLRPVMLEHPP--DTTTPSEEPGGPQMLTSQAPCVDGFE---EPGARQRALSAVSVLT
SCN4A           --------------------------------------------EKGAPRQSSSGDSGIS
SCN8A           GRLLPE------------ATTEVEIKKKGPGSLLVSMDQLA---SYGRKDRINSIMSVVT
SCN9A           GQLLPE-----------GTTNQIH-KKRRCSSYLLSEDMLN---DPNLRQRAMSRASILT
SCN3A           GQLPPE-----------GTTTETEVRKRRLSSYQISMEMLE---DSSGRQRAVSIASILT
SCN2A           GQLLPE-----------GTTTETEIRKRRSSSYHVSMDLLE---DPTSRQRAMSIASILT
SCN1A           GQLLPEVIIDKPATDDNGTTTETEMRKRRSSSFHVSMDFLE---DPSQRQRAMSIASILT
                                                            .     .         

SCN11A          IT-MKEQEKSQEPCLPCGENLASKYLVWNCCPQWLCVKKVLRTVMTDPFTELAITICIII
SCN7A           ----EELEKSKKICPLYWYKFAKTFLIWNCSPCWLKLKEFVHRIIMAPFTDLFLIICIIL
SCN10A          SV-LEELEESEQKCPPCLTSLSQKYLIWDCCPMWVKLKTILFGLVTDPFAELTITLCIVV
SCN5A           SA-LEELEESRHKCPPCWNRLAQRYLIWECCPLWMSIKQGVKLVVMDPFTDLTITMCIVL
SCN4A           DA-MEELEEAHQKCPPWWYKCAHKVLIWNCCAPWLKFKNIIHLIVMDPFVDLGITICIVL
SCN8A           NTLVEELEESQRKCPPCWYKFANTFLIWECHPYWIKLKEIVNLIVMDPFVDLAITICIVL
SCN9A           NT-VEELEESRQKCPPWWYRFAHKFLIWNCSPYWIKFKKCIYFIVMDPFVDLAITICIVL
SCN3A           NT-MEELEESRQKCPPCWYRFANVFLIWDCCDAWLKVKHLVNLIVMDPFVDLAITICIVL
SCN2A           NT-MEELEESRQKCPPCWYKFANMCLIWDCCKPWLKVKHLVNLVVMDPFVDLAITICIVL
SCN1A           NT-VEELEESRQKCPPCWYKFSNIFLIWDCSPYWLKVKHVVNLVVMDPFVDLAITICIVL
                    :* *::   *       :   *:*:*   *: .*  :  ::  **.:* : :**::

SCN11A          NTVFLAMEHHKMEASFEKMLNIGNLVFTSIFIAEMCLKIIALDPYHYFRRGWNIFDSIVA
SCN7A           NVCFLTLEHYPMSKQTNTLLNIGNLVFIGIFTAEMIFKIIAMHPYGYFQVGWNIFDSMIV
SCN10A          NTIFMAMEHHGMSPTFEAMLQIGNIVFTIFFTAEMVFKIIAFDPYYYFQKKWNIFDCIIV
SCN5A           NTLFMALEHYNMTSEFEEMLQVGNLVFTGIFTAEMTFKIIALDPYYYFQQGWNIFDSIIV
SCN4A           NTLFMAMEHYPMTEHFDNVLTVGNLVFTGIFTAEMVLKLIAMDPYEYFQQGWNIFDSIIV
SCN8A           NTLFMAMEHHPMTPQFEHVLAVGNLVFTGIFTAEMFLKLIAMDPYYYFQEGWNIFDGFIV
SCN9A           NTLFMAMEHHPMTEEFKNVLAIGNLVFTGIFAAEMVLKLIAMDPYEYFQVGWNIFDSLIV
SCN3A           NTLFMAMEHYPMTEQFSSVLTVGNLVFTGIFTAEMVLKIIAMDPYYYFQEGWNIFDGIIV
SCN2A           NTLFMAMEHYPMTEQFSSVLSVGNLVFTGIFTAEMFLKIIAMDPYYYFQEGWNIFDGFIV
SCN1A           NTLFMAMEHYPMTDHFNNVLTVGNLVFTGIFTAEMFLKIIAMDPYYYFQEGWNIFDGFIV
                *. *:::**: *    . :* :**:**  :* *** :*:**: ** **.  ***** ::.

SCN11A          LLSFADVMNCVLQKRSWPFLRSFRVLRVFKLAKSWPTLNTLIKIIGNSVGALGSLTVVLV
SCN7A           FHGLIEL--CLANVAGMALLRLFRMLRIFKLGKYWPTFQILMWSLSNSWVALKDLVLLLF
SCN10A          TVSLLEL--GVAKKGSLSVLRSFRLLRVFKLAKSWPTLNTLIKIIGNSVGALGNLTIILA
SCN5A           ILSLMEL--GLSRMSNLSVLRSFRLLRVFKLAKSWPTLNTLIKIIGNSVGALGNLTLVLA
SCN4A           TLSLVEL--GLANVQGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
SCN8A           SLSLMEL--SLADVEGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
SCN9A           TLSLVEL--FLADVEGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
SCN3A           SLSLMEL--GLSNVEGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
SCN2A           SLSLMEL--GLANVEGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
SCN1A           TLSLVEL--GLANVEGLSVLRSFRLLRVFKLAKSWPTLNMLIKIIGNSVGALGNLTLVLA
                  .: ::   :    . ..** **:**:***.* ***:: *:. :.**  ** .*.::* 

SCN11A          IVIFIFSVVGMQLFGRSFNSQKSPKLCNPTGPTVSC--LRHWHMGDFWHSFLVVFRILCG
SCN7A           TFIFFSAAFGMKLFGKNYEEF----VCHIDKD---CQ-LPRWHMHDFFHSFLNVFRILCG
SCN10A          IIVFVFALVGKQLLGENYRNN----RKNISAP---HEDWPRWHMHDFFHSFLIVFRILCG
SCN5A           IIVFIFAVVGMQLFGKNYSE------LRDSDS---GL-LPRWHMMDFFHAFLIIFRILCG
SCN4A           IIVFIFAVVGMQLFGKSYKEC----VCKIALD---CN-LPRWHMHDFFHSFLIVFRILCG
SCN8A           IIVFIFAVVGMQLFGKSYKEC----VCKINQD---CE-LPRWHMHDFFHSFLIVFRVLCG
SCN9A           IIVFIFAVVGMQLFGKSYKEC----VCKINDD---CT-LPRWHMNDFFHSFLIVFRVLCG
SCN3A           IIVFIFAVVGMQLFGKSYKEC----VCKINDD---CT-LPRWHMNDFFHSFLIVFRVLCG
SCN2A           IIVFIFAVVGMQLFGKSYKEC----VCKISND---CE-LPRWHMHDFFHSFLIVFRVLCG
SCN1A           IIVFIFAVVGMQLFGKSYKDC----VCKIASD---CQ-LPRWHMNDFFHSFLIVFRVLCG
                 .:*. : .* :*:* .: .       .            .*** **:*:** :**:***

SCN11A          EWIENMWECMQEANASSSLCVIVFILITVIGKLVVLNLFIALLLNSFSNEERNGNLEGEA
SCN7A           EWVETLWDCMEV--AGQSWCIPFYLMVILIGNLLVLYLFLA-LVSSFSSCKDVTA-EENN
SCN10A          EWIENMWACMEV--GQKSICLILFLTVMVLGNLVVLNLFIALLLNSFSADNLTAP-EDDG
SCN5A           EWIETMWDCMEV--SGQSLCLLVFLLVMVIGNLVVLNLFLALLLSSFSADNLTAP-DEDR
SCN4A           EWIETMWDCMEV--AGQAMCLTVFLMVMVIGNLVVLNLFLALLLSSFSADSLAAS-DEDG
SCN8A           EWIETMWDCMEV--AGQAMCLIVFMMVMVIGNLVVLNLFLALLLSSFSADNLAAT-DDDG
SCN9A           EWIETMWDCMEV--AGQAMCLIVYMMVMVIGNLVVLNLFLALLLSSFSSDNLTAI-EEDP
SCN3A           EWIETMWDCMEV--AGQTMCLIVFMLVMVIGNLVVLNLFLALLLSSFSSDNLAAT-DDDN
SCN2A           EWIETMWDCMEV--AGQTMCLTVFMMVMVIGNLVVLNLFLALLLSSFSSDNLAAT-DDDN
SCN1A           EWIETMWDCMEV--AGQAMCLTVFMMVMVIGNLVVLNLFLALLLSSFSADNLAAT-DDDN
                **:*.:* **:   . .: *: .:: : ::*:*:** **:* *:.***  .     : : 

SCN11A          RKTKVQLALDRFRRAFCFVRHTLEHFCHK---WCRKQNLP--------QQKEVAGGCAAQ
SCN7A           EAKNLQLAVARIKKGINYVLLKI---------LCKTQNVPKDTMDHVNEVYVKED--ISD
SCN10A          EVNNLQVALARIQVFGHRTKQALCSFFSRSCPFPQPKAEP-ELVVKLPLSSSKAENHIAA
SCN5A           EMNNLQLALARIQRGLRFVKRTTWDFCCGL--LRQRPQKP-AALAAQGQL----PSCIAT
SCN4A           EMNNLQIAIGRIKLGIGFAKAFLLGLLHGK--ILSPKDIM-LSLGEADGAGEAGEAGETA
SCN8A           EMNNLQISVIRIKKGVAWTKLKVHAFMQAH--FKQREA---DEVKPLDELYEKKANCIAN
SCN9A           DANNLQIAVTRIKKGINYVKQTLREFILKA--FSKKPKIS-REIRQAEDLNTKKENYISN
SCN3A           EMNNLQIAVGRMQKGIDYVKNKMRECFQKA--FFRKPKVI--EIHEGNKI----DSCMSN
SCN2A           EMNNLQIAVGRMQKGIDFVKRKIREFIQKA--FVRKQKAL-DEIKPLEDLNNKKDSCISN
SCN1A           EMNNLQIAVDRMHKGVAYVKRKIYEFIQQS--FIRKQKIL-DEIKPLDDLNNKKDSCMSN
                  .::*::: *:.     .                                       : 

SCN11A          --------SKDIIPLVMEMKRGSETQEELGILTSVPKTLGVRHDWTWLA---------PL
SCN7A           ------HTLSELSNTQDFLKDKEKSSGTEKNAT--------ENESQSLIPSPSVSETVPI
SCN10A          -------------------NTARGSSGGLQAPRGPRD------EHSDFIANPTVWVSVPI
SCN5A           PYSPPPPETEKVPPTRKETRFEEGEQPGQGTPGDPEP------------------VCVPI
SCN4A           ------PEDEKKEPPEEDLKKDNHILNHMGLADGPPSSL--ELDHLNFINNPYLTIQVPI
SCN8A           ------HTGADIHRNGDFQKNGNGTTSGI--GSSVEKYIIDE-DHMSFINNPNLTVRVPI
SCN9A           ------HTLAEMSKGHNFLKEKDKIS---GFGSSVDKHLMEDSDGQSFIHNPSLTVTVPI
SCN3A           ------NTGIEISKELNYLRDGNGTTSGVGTGSSVEKYVIDENDYMSFINNPSLTVTVPI
SCN2A           ------HTTIEIGKDLNYLKDGNGTTS--GIGSSVEKYVVDESDYMSFINNPSLTVTVPI
SCN1A           ------HTA-EIGKDLDYLKDVNGTTSGIGTGSSVEKYIIDESDYMSFINNPSLTVTVPI
                                   .                                      *:

SCN11A          AEEEDDVEFSGED------NAQRITQPEPEQQAYELHQENK---------------KPTS
SCN7A           ASGESDIENLDNK------EIQSKSGDGGSK---EKIK-QS-------------------
SCN10A          AEGESDLDDLEDDGGEDAQSFQQEVIPKGQQEQLQQVERCG------DHLTPRSPGTGTS
SCN5A           AVAESDTDDQEED------EENSLGTEEESSKQQESQPVSGGPEAPPDSRTWSQVSATAS
SCN4A           ASEESDLEMPTEE------ETDTFSEPEDSKKPPQPLY-DG-------------------
SCN8A           AVGESDFENLNTE------DVSSESDPEGSK---DKLD-DT-------------------
SCN9A           APGESDLENMNAE------ELSSDSDSEYSK---VRLN-RS-------------------
SCN3A           AVGESDFENLNTE------EFSSESELEESK---EKLN-AT-------------------
SCN2A           AVGESDFENLNTE------EFSSESDMEESK---EKLN-AT-------------------
SCN1A           AVGESDFENLNTE------DFSSESDLEESK---EKLNESS-------------------
                *  *.* :    .      . .       ..                             

SCN11A          QRVQSVEIDMFSEDEPHLTIQDPRKKSDVTSILSECSTIDL---QDGFGWLPEMVPKK--
SCN7A           -------------------------------SSSECSTVDIAISEE--EEMFYGG-----
SCN10A          SEDLAPSLGETWKDESVPQVPAEGVDDT---SSSEGSTVDCLDPEEILRKIPELADDLE-
SCN5A           SEAEASASQADWRQQWKAEPQAPGCGETPEDSCSEGSTADMTNTAELLEQIPDLGQDVK-
SCN4A           -------------------------------NSSVCSTADYKPPEEDPEEQAEENPEGE-
SCN8A           -------------------------------SSSEGSTIDIKPEVE---EVPVEQPEEYL
SCN9A           -------------------------------SSSECSTVDNPLPGE--GEEAEAEPMNSD
SCN3A           -------------------------------SSSEGSTVDVVLPRE--GEQAETEPEEDL
SCN2A           -------------------------------SSSEGSTVDIGAPAE--GEQPEVEPEESL
SCN1A           -------------------------------SSSEGSTVDIGAPVE---EQPVVEPEETL
                                                 *  ** *     :              

SCN11A          QPERCLPKGFGCCFPCCSVDKRKPPWVIWWNLRKTCYQIVKHSWFESFIIFVILLSSGAL
SCN7A           ERSKHLKNGCRRGSSLGQISGASKKGKIWQNIRKTCCKIVENNWFKCFIGLVTLLSTGTL
SCN10A          EPDDCFTEGCIRHCPCCKLDTTKSPWDVGWQVRKTCYRIVEHSWFESFIIFMILLSSGSL
SCN5A           DPEDCFTEGCVRRCPCCAVDTTQAPGKVWWRLRKTCYHIVEHSWFETFIIFMILLSSGAL
SCN4A           QPEECFTEACVQRWPCLYVDISQGRGKKWWTLRRACFKIVEHNWFETFIVFMILLSSGAL
SCN8A           DPDACFTEGCVQRFKCCQVNIEEGLGKSWWILRKTCFLIVEHNWFETFIIFMILLSSGAL
SCN9A           EPEACFTDGCVWRFSCCQVNIESGKGKIWWNIRKTCYKIVEHSWFESFIVLMILLSSGAL
SCN3A           KPEACFTEGCIKKFPFCQVSTEEGKGKIWWNLRKTCYSIVEHNWFETFIVFMILLSSGAL
SCN2A           EPEACFTEDCVRKFKCCQISIEEGKGKLWWNLRKTCYKIVEHNWFETFIVFMILLSSGAL
SCN1A           EPEACFTEGCVQRFKCCQINVEEGRGKQWWNLRRTCFRIVEHNWFETFIVFMILLSSGAL
                . .  : .          :.  .      . :*.:*  **::.**: ** :: ***:*:*

SCN11A          IFEDVHLENQPKIQELLNCTDIIFTHIFILEMVLKWVAFGFGKYFTSAWCCLDFIIVIVS
SCN7A           AFEDIYMDQRKTIKILLEYADMIFTYIFILEMLLKWMAYGFKAYFSNGWYRLDFVVVIVF
SCN10A          AFEDYYLDQKPTVKALLEYTDRVFTFIFVFEMLLKWVAYGFKKYFTNAWCWLDFLIVNIS
SCN5A           AFEDIYLEERKTIKVLLEYADKMFTYVFVLEMLLKWVAYGFKKYFTNAWCWLDFLIVDVS
SCN4A           AFEDIYIEQRRVIRTILEYADKVFTYIFIMEMLLKWVAYGFKVYFTNAWCWLDFLIVDVS
SCN8A           AFEDIYIEQRKTIRTILEYADKVFTYIFILEMLLKWTAYGFVKFFTNAWCWLDFLIVAVS
SCN9A           AFEDIYIERKKTIKIILEYADKIFTYIFILEMLLKWIAYGYKTYFTNAWCWLDFLIVDVS
SCN3A           AFEDIYIEQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGFQTYFTNAWCWLDFLIVDVS
SCN2A           AFEDIYIEQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGFQVYFTNAWCWLDFLIVDVS
SCN1A           AFEDIYIDQRKTIKTMLEYADKVFTYIFILEMLLKWVAYGYQTYFTNAWCWLDFLIVDVS
                 *** ::: .  :. :*: :* :**.:*::**:*** *:*:  :*:..*  ***::* : 

SCN11A          VTTLI-------NLMELKSFRTLRALRPLRALSQFEGMKVVVNALIGAIPAILNVLLVCL
SCN7A           CLSLIGKTRE-----ELKPLISMKFLRPLRVLSQFERMKVVVRALIKTTLPTLNVFLVCL
SCN10A          LISLTAKILEYSEVAPIKALRTLRALRPLRALSRFEGMRVVVDALVGAIPSIMNVLLVCL
SCN5A           LVSLVANTLGFAEMGPIKSLRTLRALRPLRALSRFEGMRVVVNALVGAIPSIMNVLLVCL
SCN4A           IISLVANWLGYSELGPIKSLRTLRALRPLRALSRFEGMRVVVNALLGAIPSIMNVLLVCL
SCN8A           LVSLIANALGYSELGAIKSLRTLRALRPLRALSRFEGMRVVVNALVGAIPSIMNVLLVCL
SCN9A           LVTLVANTLGYSDLGPIKSLRTLRALRPLRALSRFEGMRVVVNALIGAIPSIMNVLLVCL
SCN3A           LVSLVANALGYSELGAIKSLRTLRALRPLRALSRFEGMRVVVNALVGAIPSIMNVLLVCL
SCN2A           LVSLTANALGYSELGAIKSLRTLRALRPLRALSRFEGMRVVVNALLGAIPSIMNVLLVCL
SCN1A           LVSLTANALGYSELGAIKSLRTLRALRPLRALSRFEGMRVVVNALLGAIPSIMNVLLVCL
                  :*            :*.: ::. *****.**.** *.*** **: :  . :**:****

SCN11A          IFWLVFCILGVYFFSGKFGKCINGTDSVI---NYTIITNKSQCES----GN--FSWINQK
SCN7A           MIWLIFSIMGVDLFAGRFYECIDPTSGER-F-PSSEVMNKSRCESLLFNES--MLWENAK
SCN10A          IFWLIFSIMGVNLFAGKFWRCINYTDGEFSLVPLSIVNNKSDCKIQNSTGS--FFWVNVK
SCN5A           IFWLIFSIMGVNLFAGKFGRCINQTEGDLPL-NYTIVNNKSQCESLNLTGE--LYWTKVK
SCN4A           IFWLIFSIMGVNLFAGKFYYCINTTTSER-F-DISEVNNKSECESLMHTGQ--VRWLNVK
SCN8A           IFWLIFSIMGVNLFAGKYHYCFNETSEIR-F-EIEDVNNKTECEKLMEGNNTEIRWKNVK
SCN9A           IFWLIFSIMGVNLFAGKFYECINTTDGSR-F-PASQVPNRSECFALMNVSQN-VRWKNLK
SCN3A           IFWLIFSIMGVNLFAGKFYHCVNMTTGNM-F-DISDVNNLSDCQAL---GKQ-ARWKNVK
SCN2A           IFWLIFSIMGVNLFAGKFYHCINYTTGEM-F-DVSVVNNYSECKALIESNQT-ARWKNVK
SCN1A           IFWLIFSIMGVNLFAGKFYHCINTTTGDR-F-DIEDVNNHTDCLKLIERNET-ARWKNVK
                ::**:*.*:** :*:*.:  *.: *           : * : *       .    * : *

SCN11A          VNFDNVGNAYLALLQVATFKGWMDIIYAAVDSTEKEQQPEFESNSLGYIYFVVFIIFGSF
SCN7A           MNFDNVGNGFLSLLQVATFNGWITIMNSAIDSVAVNIQPHFEVNIYMYCYFINFIIFGVF
SCN10A          VNFDNVAMGYLALLQVATFKGWMDIMYAAVDSREVNMQPKWEDNVYMYLYFVIFIIFGGF
SCN5A           VNFDNVGAGYLALLQVATFKGWMDIMYAAVDSRGYEEQPQWEYNLYMYIYFVIFIIFGSF
SCN4A           VNYDNVGLGYLSLLQVATFKGWMDIMYAAVDSREKEEQPQYEVNLYMYLYFVIFIIFGSF
SCN8A           INFDNVGAGYLALLQVATFKGWMDIMYAAVDSRKPDEQPKYEDNIYMYIYFVIFIIFGSF
SCN9A           VNFDNVGLGYLSLLQVATFKGWTIIMYAAVDSVNVDKQPKYEYSLYMYIYFVVFIIFGSF
SCN3A           VNFDNVGAGYLALLQVATFKGWMDIMYAAVDSRDVKLQPVYEENLYMYLYFVIFIIFGSF
SCN2A           VNFDNVGLGYLSLLQVATFKGWMDIMYAAVDSRNVELQPKYEDNLYMYLYFVIFIIFGSF
SCN1A           VNFDNVGFGYLSLLQVATFKGWMDIMYAAVDSRNVELQPKYEESLYMYLYFVIFIIFGSF
                :*:***. .:*:*******:**  *: :*:**   . ** :* .   * **: ***** *

SCN11A          FTLNLFIGVIIDNFNQQQKKLGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPLNKCQG
SCN7A           LPLSMLITVIIDNFNKHKIKLGGSNIFITVKQRKQYRRLKKLMYEDSQRPVPRPLNKLQG
SCN10A          FTLNLFVGVIIDNFNQQKKKLGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPLNKFQG
SCN5A           FTLNLFIGVIIDNFNQQKKKLGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPLNKYQG
SCN4A           FTLNLFIGVIIDNFNQQKKKLGGKDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPQNKIQG
SCN8A           FTLNLFIGVIIDNFNQQKKKFGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPLNKIQG
SCN9A           FTLNLFIGVIIDNFNQQKKKLGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPGNKIQG
SCN3A           FTLNLFIGVIIDNFNQQKKKFGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPANKFQG
SCN2A           FTLNLFIGVIIDNFNQQKKKFGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPANKFQG
SCN1A           FTLNLFIGVIIDNFNQQKKKFGGQDIFMTEEQKKYYNAMKKLGSKKPQKPIPRPGNKFQG
                :.*.::: *******::: *:**.:**:* :*.* *. :***  :..*.*:*** ** **

SCN11A          LVFDIVTSQIFDIIIISLIILNMISMMAESYNQPKAMKSILDHLNWVFVVIFTLECLIKI
SCN7A           FIFDVVTSQAFNVIVMVLICFQAIAMMIDTDVQSLQMSIALYWINSIFVMLYTMECILKL
SCN10A          FVFDIVTRQAFDITIMVLICLNMITMMVETDDQSEEKTKILGKINQFFVAVFTGECVMKM
SCN5A           FIFDIVTKQAFDVTIMFLICLNMVTMMVETDDQSPEKINILAKINLLFVAIFTGECIVKL
SCN4A           MVYDLVTKQAFDITIMILICLNMVTMMVETDNQSQLKVDILYNINMIFIIIFTGECVLKM
SCN8A           IVFDFVTQQAFDIVIMMLICLNMVTMMVETDTQSKQMENILYWINLVFVIFFTCECVLKM
SCN9A           CIFDLVTNQAFDISIMVLICLNMVTMMVEKEGQSQHMTEVLYWINVVFIILFTGECVLKL
SCN3A           MVFDFVTRQVFDISIMILICLNMVTMMVETDDQGKYMTLVLSRINLVFIVLFTGEFVLKL
SCN2A           MVFDFVTKQVFDISIMILICLNMVTMMVETDDQSQEMTNILYWINLVFIVLFTGECVLKL
SCN1A           MVFDFVTRQVFDISIMILICLNMVTMMVETDDQSEYVTTILSRINLVFIVLFTGECVLKL
                 ::*.** * *:: :: ** :: ::** :.  *       * .:* .*: .:* * ::*:

SCN11A          FALRQYYFTNGWNLFDCVVVLLSIVSTMISTLENQEHIPFPPTLFRIVRLARIGRILRLV
SCN7A           IAFRCFYFTIAWNIFDFMVVIFSITGLCLPMTVG--SYLVPPSLVQLILLSRIIHMLRLG
SCN10A          FALRQYYFTNGWNVFDFIVVVLSIASLIFSAILKSLQSYFSPTLFRVIRLARIGRILRLI
SCN5A           AALRHYYFTNSWNIFDFVVVILSIVGTVLSDIIQ--KYFFSPTLFRVIRLARIGRILRLI
SCN4A           LALRQYYFTVGWNIFDFVVVILSIVGLALSDLIQ--KYFVSPTLFRVIRLARIGRVLRLI
SCN8A           FALRHYYFTIGWNIFDFVVVILSIVGMFLADIIE--KYFVSPTLFRVIRLARIGRILRLI
SCN9A           ISLRHYYFTVGWNIFDFVVVIISIVGMFLADLIE--TYFVSPTLFRVIRLARIGRILRLV
SCN3A           VSLRHYYFTIGWNIFDFVVVILSIVGMFLAEMIE--KYFVSPTLFRVIRLARIGRILRLI
SCN2A           ISLRYYYFTIGWNIFDFVVVILSIVGMFLAELIE--KYFVSPTLFRVIRLARIGRILRLI
SCN1A           ISLRHYYFTIGWNIFDFVVVILSIVGMFLAELIE--KYFVSPTLFRVIRLARIGRILRLI
                 ::* :*** .**:** :**::**..  :.         ..*:*..:: *:** .:*** 

SCN11A          RAARGIRTLLFALMMSLPSLFNIGLLLFLIMFIYAILGMNWFSKVNPESGIDDIFNFKTF
SCN7A           KGPKVFHNLMLPLMLSLPALLNIILLIFLVMFIYAVFGMYNFAYVKKEAGINDVSNFETF
SCN10A          RAAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYSIFGMSSFPHVRWEAGIDDMFNFQTF
SCN5A           RGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYSIFGMANFAYVKWEAGIDDMFNFQTF
SCN4A           RGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYSIFGMSNFAYVKKESGIDDMFNFETF
SCN8A           KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIFSIFGMSNFAYVKHEAGIDDMFNFETF
SCN9A           KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKKEDGINDMFNFETF
SCN3A           KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKKEAGIDDMFNFETF
SCN2A           KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKREVGIDDMFNFETF
SCN1A           KGAKGIRTLLFALMMSLPALFNIGLLLFLVMFIYAIFGMSNFAYVKREVGIDDMFNFETF
                .... :..*::.**:***:*:** **:**:***::::**  *. *. * **:*: **:**

SCN11A          ASSMLCLFQISTSAGWDSLLSPMLRSKES-CNSSSEN--------CHLPGIATSYFVSYI
SCN7A           GNSMLCLFQVAIFAGWDGMLDAIFNSKWSDCDPDKINPGTQVRGDCGNPSVGIFYFVSYI
SCN10A          ANSMLCLFQITTSAGWDGLLSPILNTGPPYCDPNLPNSNGT-RGDCGSPAVGIIFFTTYI
SCN5A           ANSMLCLFQITTSAGWDGLLSPILNTGPPYCDPTLPNSNGS-RGDCGSPAVGILFFTTYI
SCN4A           GNSIICLFEITTSAGWDGLLNPILNSGPPDCDPNLENPGTSVKGDCGNPSIGICFFCSYI
SCN8A           GNSMICLFQITTSAGWDGLLLPILN-RPPDCSLDKEHPGSGFKGDCGNPSVGIFFFVSYI
SCN9A           GNSMICLFQITTSAGWDGLLAPILNSKPPDCDPKKVHPGSSVEGDCGNPSVGIFYFVSYI
SCN3A           GNSMICLFQITTSAGWDGLLAPILNSAPPDCDPDTIHPGSSVKGDCGNPSVGIFFFVSYI
SCN2A           GNSMICLFQITTSAGWDGLLAPILNSGPPDCDPDKDHPGSSVKGDCGNPSVGIFFFVSYI
SCN1A           GNSMICLFQITTSAGWDGLLAPILNSKPPDCDPNKVNPGSSVKGDCGNPSVGIFFFVSYI
                ..*::***:::  ****.:* .::.   . *.    :        *  *.:.  :* :**

SCN11A          IISFLIVVNMYIAVILENFNTATEESEDPLGEDDFDIFYEVWEKFDPEATQFIKYSALSD
SCN7A           LISWLIIVNMYIVVVMEFLNIASKKKNKTLSEDDFRKFFQVWKRFDPDRTQYIDSSKLSD
SCN10A          IISFLIMVNMYIAVILENFNVATEESTEPLSEDDFDMFYETWEKFDPEATQFITFSALSD
SCN5A           IISFLIVVNMYIAIILENFSVATEESTEPLSEDDFDMFYEIWEKFDPEATQFIEYSVLSD
SCN4A           IISFLIVVNMYIAIILENFNVATEESSEPLGEDDFEMFYETWEKFDPDATQFIAYSRLSD
SCN8A           IISFLIVVNMYIAIILENFSVATEESADPLSEDDFETFYEIWEKFDPDATQFIEYCKLAD
SCN9A           IISFLVVVNMYIAVILENFSVATEESTEPLSEDDFEMFYEVWEKFDPDATQFIEFSKLSD
SCN3A           IISFLVVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPDATQFIEFSKLSD
SCN2A           IISFLVVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPDATQFIEFAKLSD
SCN1A           IISFLVVVNMYIAVILENFSVATEESAEPLSEDDFEMFYEVWEKFDPDATQFMEFEKLSQ
                :**:*::*****.:::* :. *:::. ..*.****  *:: *:.***: **::    *::

SCN11A          FADALPEPLRVAKPNKYQFLVMDLPMVSEDRLHCMDILFAFTARVLGGSDGLDSMKAMME
SCN7A           FAAALDPPLFMAKPNKGQLIALDLPMAVGDRIHCLDILLAFTKRVMGQDVRMEKVVSEIE
SCN10A          FADTLSGPLRIPKPNRNILIQMDLPLVPGDKIHCLDILFAFTKNVLGESGELDSLKANME
SCN5A           FADALSEPLRIAKPNQISLINMDLPMVSGDRIHCMDILFAFTKRVLGESGEMDALKIQME
SCN4A           FVDTLQEPLRIAKPNKIKLITLDLPMVPGDKIHCLDILFALTKEVLGDSGEMDALKQTME
SCN8A           FADALEHPLRVPKPNTIELIAMDLPMVSGDRIHCLDILFAFTKRVLGDSGELDILRQQME
SCN9A           FAAALDPPLLIAKPNKVQLIAMDLPMVSGDRIHCLDILFAFTKRVLGESGEMDSLRSQME
SCN3A           FAAALDPPLLIAKPNKVQLIAMDLPMVSGDRIHCLDILFAFTKRVLGESGEMDALRIQME
SCN2A           FADALDPPLLIAKPNKVQLIAMDLPMVSGDRIHCLDILFAFTKRVLGESGEMDALRIQME
SCN1A           FAAALEPPLNLPQPNKLQLIAMDLPMVSGDRIHCLDILFAFTKRVLGESGEMDALRIQME
                *. :*  ** :.:**   :: :***:.  *.:**:***:*:*  *:* .  :: :   :*

SCN11A          EKFMEANPLKKLYEPIVTTTKRKEEERGAAIIQKAFRKYMMK----------VTKGDQG-
SCN7A           SGFLLANPFKITCEPITTTLKRKQEAVSATIIQRAYKNYRLRRNDKNTSDIHMIDGDRD-
SCN10A          EKFMATNLSKSSYEPIATTLRWKQEDISATVIQKAYRSYVLHRSMALSNTPCVPRAEEE-
SCN5A           EKFMAANPSKISYEPITTTLRRKHEEVSAMVIQRAFRRHLLQRSLKHASFLFRQQAGSGL
SCN4A           EKFMAANPSKVSYEPITTTLKRKHEEVCAIKIQRAYRRHLLQRSMKQASYMYRHSHDGS-
SCN8A           ERFVASNPSKVSYEPITTTLRRKQEEVSAVVLQRAYRGHLARR-----------------
SCN9A           ERFMSANPSKVSYEPITTTLKRKQEDVSATVIQRAYRRYRLRQNVKNISSIYIKDGDRD-
SCN3A           DRFMASNPSKVSYEPITTTLKRKQEEVSAAIIQRNFRCYLLKQRLKNISSNYNKEAIKG-
SCN2A           ERFMASNPSKVSYEPITTTLKRKQEEVSAIIIQRAYRRYLLKQKVKKVSSIYKKDKGKE-
SCN1A           ERFMASNPSKVSYQPITTTLKRKQEEVSAVIIQRAYRRHLLKRTVKQASFTYNKNKIKG-
                . *: :*  *   :**.** ..* *   *  :*. :. :  .                  

SCN11A          ------DQNDLE-----------NGPHSP------------------LQTL-CNGDLSSF
SCN7A           ---VHATKEGAYFDKA-------KE---------------------------KSPIQSQI
SCN10A          -AASLPD-EGFVAFTA-------NENCVL---PDKSETASATSFPPSYESV-TRGLSDRV
SCN5A           SEEDAPEREGLIAYVM-------SENFSRPLGPPSSSSISSTSFPPSYDSV-TRATSDNL
SCN4A           -GDDAPEKEGLLANTMSKMYGHENGNSSS---PSPEEKGEAGDAGPTMGLMPISPSDTAW
SCN8A           ---GFICKKTTSNKLE-------NGGTHR---EKKESTPSTAS-LPSYDSV-TKPEKEKQ
SCN9A           --DDLLNKKDMAFDNV-------NENSSP---EKTDATSSTTS-PPSYDSV-TKPDKEKY
SCN3A           -RIDLPIKQDMIIDKL-------NGNSTP---EKTDGSSSTTS-PPSYDSV-TKPDKEKF
SCN2A           -CDGTPIKEDTLIDKL-------NENSTP---EKTDMTPSTTS-PPSYDSV-TKPEKEKF
SCN1A           -GANLLIKEDMIIDRI-------NENSIT---EKTDLTMSTAACPPSYDRV-TKPIVEKH
                        :              .                                    

SCN11A          GV-AKGKVHCD-----------------
SCN7A           ----------------------------
SCN10A          NMRTSSSIQNEDEA----TSMELIAPGP
SCN5A           QVRGSDYSHSEDLADFPPSPDRDRESIV
SCN4A           ---PPAPPPGQTVR------PGVKESLV
SCN8A           QRAEEGRRERAKRQ------KEVRESKC
SCN9A           ---EQDRTEKEDKG------KDSKESKK
SCN3A           ---EKDKPEKESKG------KEVRENQK
SCN2A           ---EKDKSEKEDKG------KDIRESKK
SCN1A           ----------EQEG------KDEKAKGK
                                            
